import type { BlogPostMeta } from './blog-posts'
import type { BlogAnswerPost } from './blog-answers'

const date = '2026-05-27'

export const BLOG_TRENDING_POSTS: BlogPostMeta[] = [
  { slug: 'ai-agent-credit-card-safety-checklist', title: 'AI agent credit card safety checklist for production teams', description: 'How to let AI agents spend safely using wallet segmentation, spending limits, approvals, and signed execution controls.', publishedAt: date, tags: ['agentic-commerce', 'payments', 'security', 'ai-agents'], readTime: 6, featured: true },
  { slug: 'agentic-commerce-fraud-prevention', title: 'Agentic commerce fraud prevention: what actually works', description: 'A practical fraud model for autonomous shopping flows: identity proof, authorization, policy gates, and dispute-ready logs.', publishedAt: date, tags: ['agentic-commerce', 'fraud', 'payments', 'runtime-trust'], readTime: 7 },
  { slug: 'can-ai-agents-buy-online-safely', title: 'Can AI agents buy online safely?', description: 'Yes, if you enforce pre-execution controls, constrained wallets, approval thresholds, and auditable purchase intents.', publishedAt: date, tags: ['ai-agents', 'ecommerce', 'payments', 'human-in-the-loop'], readTime: 6 },
  { slug: 'autonomous-trading-agent-risk-controls', title: 'Autonomous trading agent risk controls for retail and enterprise', description: 'Risk patterns and controls for AI-driven trading and spending agents, including dedicated capital pools and real-time override.', publishedAt: date, tags: ['trading', 'finance', 'risk-management', 'ai-agents'], readTime: 7 },
  { slug: 'ai-agent-spending-limits-and-wallet-segmentation', title: 'AI agent spending limits and wallet segmentation', description: 'Separate agent budgets from primary accounts, cap loss, and require verification above thresholds to prevent runaway purchases.', publishedAt: date, tags: ['payments', 'wallets', 'security', 'operations'], readTime: 6 },
  { slug: 'shadow-ai-agents-and-unauthorized-purchases', title: 'Shadow AI agents and unauthorized purchases: detection and containment', description: 'How teams identify unapproved autonomous spending paths and rapidly contain them with policy controls and kill switches.', publishedAt: date, tags: ['shadow-it', 'security', 'incident-response', 'agentic-commerce'], readTime: 6 },
  { slug: 'chargebacks-and-ai-agent-transactions', title: 'Chargebacks and AI agent transactions: designing for disputes', description: 'Design transaction and action logs so payment disputes can be resolved with evidence of approval, identity, and execution scope.', publishedAt: date, tags: ['payments', 'audit-log', 'compliance', 'ai-agents'], readTime: 6 },
  { slug: 'ai-agent-payments-approval-workflows', title: 'AI agent payments approval workflows that do not kill conversion', description: 'How to route only meaningful payment risk to human review and keep low-risk automation fast and natural for users.', publishedAt: date, tags: ['payments', 'workflow', 'human-in-the-loop', 'product'], readTime: 6 },
  { slug: 'prompt-injection-in-shopping-agents', title: 'Prompt injection in shopping agents: real attack paths and defenses', description: 'How malicious product pages and external content can hijack buying agents, and what runtime controls stop bad purchases.', publishedAt: date, tags: ['prompt-injection', 'agentic-commerce', 'llm-security', 'ai-agents'], readTime: 7 },
  { slug: 'mcp-payment-tools-security', title: 'MCP payment tools security: safely exposing checkout actions', description: 'Best practices for MCP payment tools, including strict argument validation and pre-execution authorization for money movement.', publishedAt: date, tags: ['mcp', 'payments', 'tool-use', 'security'], readTime: 7 },
  { slug: 'compute-scarcity-and-ai-agent-reliability', title: 'Compute scarcity and AI agent reliability', description: 'What GPU and infra scarcity means for autonomous reliability, degraded behavior, and safe fallback policy design.', publishedAt: date, tags: ['compute', 'reliability', 'ai-governance', 'operations'], readTime: 6 },
  { slug: 'gpu-scarcity-risk-for-safety-systems', title: 'GPU scarcity risk for safety-critical AI systems', description: 'How resource shortages can pressure teams into unsafe shortcuts and how runtime policies preserve safety under constraints.', publishedAt: date, tags: ['gpu', 'safety', 'risk-management', 'ai-agents'], readTime: 6 },
  { slug: 'cost-pressure-causes-unsafe-agent-shortcuts', title: 'Cost pressure causes unsafe agent shortcuts: how to prevent it', description: 'Avoid accidental safety regressions when teams optimize for compute spend by enforcing non-negotiable action controls.', publishedAt: date, tags: ['cost', 'security', 'operations', 'policy-engine'], readTime: 6 },
  { slug: 'degraded-mode-policies-during-infrastructure-outages', title: 'Degraded-mode policies during AI infrastructure outages', description: 'Define what agents can and cannot do during model/provider outages so failures fail safe instead of failing open.', publishedAt: date, tags: ['outages', 'offline', 'policy-engine', 'ai-safety'], readTime: 6 },
  { slug: 'embodied-ai-safety-near-humans', title: 'Embodied AI safety near humans: practical runtime controls', description: 'How to gate robot actions around people with context-aware verification, blast-radius scoring, and emergency stop guarantees.', publishedAt: date, tags: ['embodied-ai', 'robotics', 'safety', 'verification'], readTime: 7 },
  { slug: 'robot-flood-road-failure-lessons', title: 'Robot flood-road failure lessons for autonomous fleets', description: 'What recurring autonomy failures teach us about hard-stop policy, weather constraints, and fleet-level containment controls.', publishedAt: date, tags: ['robotics', 'fleet', 'incident-response', 'safety'], readTime: 6 },
  { slug: 'delivery-robot-sidewalk-safety-policies', title: 'Delivery robot sidewalk safety policies operators should enforce', description: 'From pedestrian obstruction to collision risk: policy patterns for safer deployment of autonomous delivery fleets.', publishedAt: date, tags: ['delivery-robots', 'robotics', 'policy-engine', 'public-safety'], readTime: 6 },
  { slug: 'physical-world-prompt-injection-robots', title: 'Physical-world prompt injection in robots: what teams miss', description: 'How misleading text in environments can influence embodied AI and why tool/action controls must not trust model perception alone.', publishedAt: date, tags: ['prompt-injection', 'embodied-ai', 'robotics', 'llm-security'], readTime: 7 },
  { slug: 'healthcare-ai-agent-life-critical-decisions', title: 'Healthcare AI agents and life-critical decisions', description: 'Where human approval is mandatory for safety and compliance, and how runtime controls reduce patient risk in autonomous workflows.', publishedAt: date, tags: ['healthcare', 'ai-agents', 'human-in-the-loop', 'compliance'], readTime: 7 },
  { slug: 'ai-triage-systems-human-override-patterns', title: 'AI triage systems: human override patterns that actually work', description: 'Practical override and escalation patterns for high-stakes triage decisions where missed edge cases can harm people.', publishedAt: date, tags: ['triage', 'healthcare', 'human-in-the-loop', 'operations'], readTime: 6 },
  { slug: 'aviation-style-checklists-for-ai-operations', title: 'Aviation-style checklists for AI operations teams', description: 'Borrowing proven safety discipline from aviation to run autonomous agents with clear authority, handoff, and override behavior.', publishedAt: date, tags: ['operations', 'checklists', 'ai-safety', 'governance'], readTime: 6 },
  { slug: 'ai-agent-skill-decay-and-operator-readiness', title: 'AI agent skill decay and operator readiness', description: 'How over-automation erodes human judgment and what to measure so operators stay effective during incidents.', publishedAt: date, tags: ['human-in-the-loop', 'operations', 'governance', 'training'], readTime: 6 },
  { slug: 'timeout-should-not-mean-auto-approval', title: 'Timeout should not mean auto-approval in AI workflows', description: 'Why timeout-equals-approval is a governance failure and how to use escalation and safe defaults instead.', publishedAt: date, tags: ['human-in-the-loop', 'workflow', 'risk-management', 'policy-engine'], readTime: 5 },
  { slug: 'dual-approval-for-high-risk-actions', title: 'Dual approval for high-risk AI actions: when and how', description: 'Designing two-person approval flows for irreversible or regulated actions without overwhelming operators.', publishedAt: date, tags: ['dual-approval', 'compliance', 'verification', 'ai-governance'], readTime: 6 },
  { slug: 'ai-agent-trust-framework-for-enterprises', title: 'AI agent trust framework for enterprises', description: 'A simple, defensible framework to operationalize trust: identity, policy, verification, execution proof, and audit.', publishedAt: date, tags: ['enterprise', 'trust', 'governance', 'ai-agents'], readTime: 7 },
  { slug: 'ai-agent-governance-for-finance-teams', title: 'AI agent governance for finance teams', description: 'How finance leaders can control autonomous spend, approvals, and policy exceptions while preserving automation speed.', publishedAt: date, tags: ['finance', 'governance', 'agentic-commerce', 'risk-management'], readTime: 6 },
  { slug: 'ai-agent-governance-for-healthcare-teams', title: 'AI agent governance for healthcare teams', description: 'Governance controls for patient-facing autonomy: policy packs, role-scoped approvals, and audit-grade evidence.', publishedAt: date, tags: ['healthcare', 'governance', 'compliance', 'ai-agents'], readTime: 6 },
  { slug: 'ai-agent-governance-for-industrial-automation', title: 'AI agent governance for industrial automation', description: 'How to manage autonomous industrial actions with safety interlocks, approval boundaries, and incident-ready controls.', publishedAt: date, tags: ['industrial', 'automation', 'safety', 'governance'], readTime: 6 },
  { slug: 'what-happens-when-ai-agent-is-hacked', title: 'What happens when an AI agent is hacked? Response blueprint', description: 'Containment-first incident playbook for compromised agents, including kill switch, evidence capture, and controlled recovery.', publishedAt: date, tags: ['incident-response', 'security', 'ai-agents', 'operations'], readTime: 7 },
  { slug: 'can-ai-agents-have-legal-accountability', title: 'Can AI agents have legal accountability? What teams should do now', description: 'A practical view of accountability today: organizations remain responsible, so runtime controls and evidence are non-negotiable.', publishedAt: date, tags: ['legal', 'compliance', 'ai-governance', 'audit-log'], readTime: 6 },
  { slug: 'building-customer-trust-in-agentic-products', title: 'Building customer trust in agentic products', description: 'Trust is earned with clear controls, explainable approvals, and transparent action evidence—not by marketing claims.', publishedAt: date, tags: ['trust', 'product', 'agentic-commerce', 'governance'], readTime: 6 },
  { slug: 'ai-agent-audit-trails-for-dispute-resolution', title: 'AI agent audit trails for dispute resolution', description: 'Design logs that settle disputes fast: intent, policy decision, approver, execution proof, and immutable timestamps.', publishedAt: date, tags: ['audit-log', 'payments', 'disputes', 'compliance'], readTime: 6 },
  { slug: 'safe-defaults-for-autonomous-ai', title: 'Safe defaults for autonomous AI systems', description: 'Set secure baseline behavior so ambiguity and outages fail safe, not open. A practical default policy starter set.', publishedAt: date, tags: ['safe-defaults', 'ai-safety', 'policy-engine', 'operations'], readTime: 6 },
  { slug: 'red-teaming-agentic-commerce-scenarios', title: 'Red-teaming agentic commerce scenarios', description: 'How to test real-world shopping and payment attack chains before incidents happen in production.', publishedAt: date, tags: ['red-team', 'agentic-commerce', 'security', 'testing'], readTime: 7 },
  { slug: 'preventing-consent-fatigue-in-approval-queues', title: 'Preventing consent fatigue in AI approval queues', description: 'Reduce rubber-stamping by calibrating policy thresholds, improving context UX, and measuring approval quality.', publishedAt: date, tags: ['human-in-the-loop', 'ux', 'operations', 'verification'], readTime: 6 },
  { slug: 'secure-agent-wallet-architecture', title: 'Secure agent wallet architecture for autonomous spending', description: 'Blueprint for dedicated wallets, scoped credentials, and revocation controls that limit financial blast radius.', publishedAt: date, tags: ['wallets', 'payments', 'security', 'architecture'], readTime: 6 },
  { slug: 'map-agent-actions-to-business-risk', title: 'Map agent actions to business risk in 5 steps', description: 'A practical risk mapping method to decide which actions auto-approve, verify, block, or require dual approval.', publishedAt: date, tags: ['risk-management', 'policy-engine', 'ai-governance', 'operations'], readTime: 6 },
  { slug: 'ai-agent-stop-button-design', title: 'AI agent stop button design: how to make it actually work', description: 'A stop button is only useful if it is immediate, global, auditable, and tested. Design patterns for reliable containment.', publishedAt: date, tags: ['kill-switch', 'incident-response', 'ai-safety', 'fleet'], readTime: 6 },
  { slug: 'trustworthy-robotics-rollout-checklist', title: 'Trustworthy robotics rollout checklist', description: 'Pre-launch and post-launch controls for embodied AI deployments in public, enterprise, and regulated environments.', publishedAt: date, tags: ['robotics', 'embodied-ai', 'checklist', 'safety'], readTime: 7 },
  { slug: 'from-observability-to-runtime-enforcement', title: 'From observability to runtime enforcement: maturity path', description: 'How teams evolve from passive monitoring to proactive action control with policy, verification, and execution proof.', publishedAt: date, tags: ['observability', 'runtime-trust', 'maturity', 'ai-agents'], readTime: 6 },
]

const genericAnswers = [
  {
    question: 'How do we lower risk without slowing teams down?',
    answer:
      'Use risk-tiered policy so only high-impact actions require human verification, while low-risk actions continue automatically with audit.',
  },
  {
    question: 'What should we implement first?',
    answer:
      'Start with pre-execution gating for irreversible actions, then add approval SLA, escalation, and policy replay.',
  },
  {
    question: 'Where does Sanctum fit?',
    answer:
      'Sanctum sits at the action boundary so teams can approve, verify, or block side effects before execution with clear audit evidence.',
  },
]

function mk(intro: string, related: string[]): BlogAnswerPost {
  return {
    intro,
    keyPoints: [
      'Control must run at execution time, not only in prompts or post-hoc dashboards.',
      'Policies should be explicit, versioned, and mapped to business risk.',
      'Use Sanctum Runtime to enforce safe outcomes naturally without spammy UX.',
    ],
    checklist: [
      'Classify actions by impact and irreversibility.',
      'Route risky actions to verification with clear operator context.',
      'Log decisions and execution receipts for replay and compliance.',
    ],
    answers: genericAnswers,
    related,
  }
}

export const BLOG_TRENDING_ANSWERS: Record<string, BlogAnswerPost> = {
  'ai-agent-credit-card-safety-checklist': mk('Credit-card-capable agents need hard boundaries: segmented wallets, spend caps, and policy checks before checkout. This keeps convenience while preventing silent financial damage.', ['agentic-commerce-fraud-prevention', 'ai-agent-spending-limits-and-wallet-segmentation']),
  'agentic-commerce-fraud-prevention': mk('Fraud in agentic commerce is mostly an authorization and accountability problem. Teams need trusted identity, signed intent, and pre-execution policy controls.', ['ai-agent-credit-card-safety-checklist', 'chargebacks-and-ai-agent-transactions']),
  'can-ai-agents-buy-online-safely': mk('Online purchasing can be safe if teams limit authority and enforce verification above risk thresholds. The model should never be the final authority on spending.', ['ai-agent-payments-approval-workflows', 'secure-agent-wallet-architecture']),
  'autonomous-trading-agent-risk-controls': mk('Trading autonomy magnifies operational and compliance risk. Keep execution scoped to dedicated budgets and enforce manual verification for high-volatility moves.', ['ai-agent-governance-for-finance-teams', 'ai-agent-stop-button-design']),
  'ai-agent-spending-limits-and-wallet-segmentation': mk('Dedicated wallets and strict spend limits convert catastrophic risk into controlled risk. Segmentation is one of the fastest practical safeguards.', ['secure-agent-wallet-architecture', 'ai-agent-credit-card-safety-checklist']),
  'shadow-ai-agents-and-unauthorized-purchases': mk('Shadow agents emerge when teams deploy automation outside governance controls. Detection plus immediate containment prevents prolonged financial exposure.', ['what-happens-when-ai-agent-is-hacked', 'ai-agent-incident-response-runbook']),
  'chargebacks-and-ai-agent-transactions': mk('Disputes are easier when every action has evidence: who authorized, what policy allowed it, and what exactly executed. Audit quality is a product feature.', ['ai-agent-audit-trails-for-dispute-resolution', 'can-ai-agents-be-soc2-compliant']),
  'ai-agent-payments-approval-workflows': mk('Great approval UX balances safety and speed. Only meaningful risk should interrupt users, and operators need context-rich review screens.', ['preventing-consent-fatigue-in-approval-queues', 'how-to-stop-ai-agents-from-sending-emails-without-approval']),
  'prompt-injection-in-shopping-agents': mk('Shopping agents can be manipulated by untrusted product content and hidden instructions. Runtime controls and source-trust classification block unsafe purchases.', ['indirect-prompt-injection-source-trust', 'how-to-prevent-ai-agent-data-exfiltration']),
  'mcp-payment-tools-security': mk('MCP payment tools should be treated like critical transaction APIs with strict schema validation, scoped credentials, and pre-execution verification.', ['mcp-server-action-gate', 'how-to-validate-tool-arguments-in-mcp']),
  'compute-scarcity-and-ai-agent-reliability': mk('Scarce infrastructure can increase failure rates and bad fallback behavior. Teams need explicit degraded-mode policy to remain safe under resource stress.', ['degraded-mode-policies-during-infrastructure-outages', 'safe-defaults-for-autonomous-ai']),
  'gpu-scarcity-risk-for-safety-systems': mk('GPU constraints can trigger silent model downgrades and rushed architecture choices. Safety controls should not depend on best-case compute availability.', ['compute-scarcity-and-ai-agent-reliability', 'cost-pressure-causes-unsafe-agent-shortcuts']),
  'cost-pressure-causes-unsafe-agent-shortcuts': mk('Cost optimization should never bypass action controls. Governance teams should enforce non-negotiable safety checks despite performance pressure.', ['map-agent-actions-to-business-risk', 'ai-agent-security-checklist-for-production']),
  'degraded-mode-policies-during-infrastructure-outages': mk('Outages are inevitable; unsafe autonomy is optional. Define fail-safe policy before incidents, including auto-block rules for high-impact actions.', ['can-you-run-ai-agent-security-offline', 'safe-defaults-for-autonomous-ai']),
  'embodied-ai-safety-near-humans': mk('Embodied systems operate around people, so action gating must account for physical harm, reversibility, and emergency stop behavior.', ['embodied-ai-robotics-policy-gate', 'trustworthy-robotics-rollout-checklist']),
  'robot-flood-road-failure-lessons': mk('Recurring autonomy failures show why environmental edge cases need hard-stop logic and fleet-level containment controls.', ['ai-agent-kill-switch-best-practices', 'fleet-kill-switch-autonomous-systems']),
  'delivery-robot-sidewalk-safety-policies': mk('Public-space robots require conservative policy defaults around crowds, sidewalks, and visibility conditions to avoid avoidable harm.', ['trustworthy-robotics-rollout-checklist', 'embodied-ai-safety-near-humans']),
  'physical-world-prompt-injection-robots': mk('Physical text and signage can influence embodied AI decisions. Runtime policy should treat perception outputs as untrusted and verify critical actions.', ['indirect-prompt-injection-source-trust', 'ros2-safety-policy-runtime']),
  'healthcare-ai-agent-life-critical-decisions': mk('Healthcare autonomy needs strict role-scoped controls and explicit human accountability for high-impact decisions.', ['healthcare-robotics-phi-policy-packs', 'what-is-human-in-the-loop-for-ai-agents']),
  'ai-triage-systems-human-override-patterns': mk('Triage systems should default to clear human override when confidence or context quality is weak. Override pathways should be rehearsed, not theoretical.', ['timeout-should-not-mean-auto-approval', 'ai-agent-skill-decay-and-operator-readiness']),
  'aviation-style-checklists-for-ai-operations': mk('Aviation-style operational discipline improves AI reliability: checklists, challenge-response, debrief loops, and explicit authority boundaries.', ['ai-agent-incident-response-runbook', 'ai-agent-security-checklist-for-production']),
  'ai-agent-skill-decay-and-operator-readiness': mk('If humans never practice intervention, oversight becomes symbolic. Teams should measure and train real intervention readiness.', ['what-is-human-in-the-loop-for-ai-agents', 'ai-agent-approval-sla-and-escalation-design']),
  'timeout-should-not-mean-auto-approval': mk('Auto-approval on timeout rewards inaction and creates governance blind spots. Better defaults are escalation or safe deny.', ['ai-agent-approval-sla-and-escalation-design', 'preventing-consent-fatigue-in-approval-queues']),
  'dual-approval-for-high-risk-actions': mk('Dual approval is useful for irreversible or regulated actions when single-operator risk is too high. Use it selectively to avoid review bottlenecks.', ['ai-agent-policy-versioning-and-replay', 'can-ai-agents-be-soc2-compliant']),
  'ai-agent-trust-framework-for-enterprises': mk('Enterprise trust requires consistent controls across teams, providers, and devices. Action-layer enforcement unifies governance without slowing product teams.', ['can-openai-claude-gemini-share-one-agent-control-plane', 'what-is-agentic-ai-risk-management']),
  'ai-agent-governance-for-finance-teams': mk('Finance teams need visibility and control over autonomous spend before transactions settle. Policy and approvals must be first-class financial controls.', ['ai-agent-credit-card-safety-checklist', 'autonomous-trading-agent-risk-controls']),
  'ai-agent-governance-for-healthcare-teams': mk('Healthcare governance should emphasize patient safety, role-based authority, and audit-ready evidence over generic AI dashboards.', ['healthcare-ai-agent-life-critical-decisions', 'can-ai-agents-be-soc2-compliant']),
  'ai-agent-governance-for-industrial-automation': mk('Industrial autonomy benefits from strict action classes, safety interlocks, and fast operator intervention controls.', ['workflow-automation-ai-governance', 'ai-agent-stop-button-design']),
  'what-happens-when-ai-agent-is-hacked': mk('When agents are compromised, the first priority is stopping side effects. Fast containment and evidence capture determine recovery quality.', ['ai-agent-incident-response-runbook', 'ai-agent-kill-switch-best-practices']),
  'can-ai-agents-have-legal-accountability': mk('Organizations still carry accountability for autonomous actions. Governance maturity depends on verifiable controls and defensible evidence.', ['ai-agent-audit-trails-for-dispute-resolution', 'soc2-nist-ai-rmf-runtime-evidence']),
  'building-customer-trust-in-agentic-products': mk('Customers trust products that show clear control boundaries and transparent action history. Safety communication should be specific, not vague.', ['runtime-authorization-vs-guardrails-explained', 'from-observability-to-runtime-enforcement']),
  'ai-agent-audit-trails-for-dispute-resolution': mk('Dispute resolution quality depends on event completeness and traceability. Teams should design logs for legal and operational clarity from day one.', ['how-to-audit-ai-agent-decisions', 'chargebacks-and-ai-agent-transactions']),
  'safe-defaults-for-autonomous-ai': mk('Safe defaults reduce incident probability before advanced tuning begins. Default policy should assume uncertainty and protect users first.', ['ai-agent-security-checklist-for-production', 'how-to-design-ai-agent-policies-that-scale']),
  'red-teaming-agentic-commerce-scenarios': mk('Red-team scenarios reveal cross-tool attack chains that unit tests miss. Commerce and payment flows should be tested with adversarial inputs regularly.', ['prompt-injection-in-shopping-agents', 'mcp-server-security-checklist-2026']),
  'preventing-consent-fatigue-in-approval-queues': mk('Approval fatigue degrades safety over time. Tune thresholds and context UX so operator attention is reserved for truly risky actions.', ['ai-agent-approval-sla-and-escalation-design', 'how-to-approve-ai-agent-actions-on-mobile']),
  'secure-agent-wallet-architecture': mk('Secure wallet design should assume compromise and limit blast radius with isolated balances, revocation, and policy-driven controls.', ['ai-agent-spending-limits-and-wallet-segmentation', 'agentic-commerce-fraud-prevention']),
  'map-agent-actions-to-business-risk': mk('Risk mapping clarifies which actions should auto-approve, verify, or block. Clear classification makes governance consistent across teams.', ['how-to-design-ai-agent-policies-that-scale', 'ai-agent-trust-framework-for-enterprises']),
  'ai-agent-stop-button-design': mk('A stop button must be immediate, broad enough to contain harm, and auditable so post-incident analysis is reliable.', ['fleet-kill-switch-autonomous-systems', 'ai-agent-kill-switch-best-practices']),
  'trustworthy-robotics-rollout-checklist': mk('Robotics rollouts should treat safety and governance as launch criteria, not post-launch cleanup tasks.', ['embodied-ai-safety-near-humans', 'delivery-robot-sidewalk-safety-policies']),
  'from-observability-to-runtime-enforcement': mk('Mature teams evolve from reporting-only dashboards to controls that stop unsafe actions before execution. This is the shift from visibility to trust.', ['what-is-ai-agent-observability-vs-control', 'runtime-trust-layer-for-ai-agents']),
}
